# build reStructuredText documentation
---
language: python
python:
  - "2.7"
install: "pip install -q -r requirements.txt --use-mirrors"
script: sphinx-build -n -t simp_5_1_0 -b html -d _build/sphinx_cache docs/ _build/html
