---
dist: trusty
sudo: false
language: python
python:
  - 2.7
install:
  - pip install -q -r requirements.txt
script:
  - sphinx-build -E -n -b linkcheck docs linkcheck
  - sphinx-build -n -b html -d sphinx_cache docs html
